version: "3.7"
services:
  server:
    build: ./server
    depends_on:
      - client
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./server:/code
      - ./client/public:/client/public
    environment:
      - SECRET_KEY=${SECRET_KEY:?required}
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - FORWARDED_ALLOW_IPS="*"
  client:
    build: ./client
    command: "${FRONTEND_CMD}"
    volumes:
      - ./client:/code
      - /code/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}

  nginx:
    build: ./nginx
    depends_on:
      - client
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
