version: "3.7"
services:
  server:
    build: backend
    image: rickmikegull/portfolio-backend
    depends_on:
      - client
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/code
      - ./frontend/public:/frontend/public
    environment:
      - SECRET_KEY=${SECRET_KEY:?required}
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - FORWARDED_ALLOW_IPS="*"
  client:
    build: frontend
    image: rickmikegull/portfolio-frontend
    command: "${FRONTEND_CMD}"
    volumes:
      - ./frontend:/code
      - /code/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}

  nginx:
    build: ./nginx
    image: rickmikegull/portfolio-server
    depends_on:
      - client
      - server
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/nginx2.conf
    ports:
      - 80:80
