version: "3.7"
services:
  backend:
    build: backend
    image: rickmikegull/portfolio-backend
    command: ["uwsgi", "uwsgi.ini"]
    depends_on:
      - frontend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/code
      - ./frontend/public:/frontend/public
    environment:
      - SECRET_KEY=${SECRET_KEY:?required}
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - FORWARDED_ALLOW_IPS="*"
  frontend:
    build: frontend
    image: rickmikegull/portfolio-frontend
    command: "${FRONTEND_CMD}"
    volumes:
      - ./frontend:/code
      - /code/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}

  nginx:
    build: ./nginx
    image: rickmikegull/portfolio-server
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
